version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "UKHomeOffice/hocs-core"
