---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: hocs-workflow
  name: hocs-workflow
spec:
  ports:
    - name: https
      port: 443
      targetPort: 10443
  selector:
    name: hocs-workflow