---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
    - tag
  branch:
    - main

steps:
  - name: checkout
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.0.0
    commands:
      - git fetch --tags
      - git checkout ${DRONE_TAG}
      - git submodule update --init --recursive

  - &deploy
    name: cs-dev
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.0.0
    environment:
      CHART_NAME: hocs-workflow
      KUBE_CLUSTER: acp-notprod
      KUBE_NAMESPACE: cs-dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_notprod
      VERSION: ${DRONE_TAG}
    commands:
      - ./ci/helm/helm-deploy.sh --values ./helm/values-notprod.yaml --values ./helm/values-dev.yaml
    depends_on:
      - checkout

  - <<: *deploy
    name: wcs-dev
    environment:
      KUBE_NAMESPACE: wcs-dev
    depends_on:
      - cs-dev
---
kind: pipeline
type: kubernetes
name: promote
trigger:
  event:
    - promote

environment:
  CHART_NAME: hocs-workflow
  KUBE_CLUSTER: acp-notprod
  KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk

steps:
  - name: checkout
    image: alpine/git
    commands:
      - git fetch --tags
      - git checkout ${VERSION}
      - git submodule update --init --recursive

  - name: dev
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.0.0
    environment:
      KUBE_NAMESPACE: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: cs_notprod
    commands:
      - ./ci/helm/helm-deploy.sh --values ./helm/values-notprod.yaml --values ./helm/values-dev.yaml
    depends_on:
      - checkout
    when:
      target:
        - "*-dev"

  - name: cs-qa
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.0.0
    environment:
      KUBE_NAMESPACE: cs-qa
      KUBE_TOKEN:
        from_secret: cs_notprod
    commands:
      - ./ci/helm/helm-deploy.sh --values ./helm/values-notprod.yaml --values ./helm/values-qa.yaml
    depends_on:
      - checkout
    when:
      target:
        - cs-qa
        - release

  - name: wcs-qa
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.0.0
    environment:
      KUBE_NAMESPACE: wcs-qa
      KUBE_TOKEN:
        from_secret: cs_notprod
    commands:
      - ./ci/helm/helm-deploy.sh --values ./helm/values-notprod.yaml --values ./helm/values-qa.yaml
    depends_on:
      - cs-qa
    when:
      target:
        - wcs-qa
        - release

  - name: demo
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.0.0
    environment:
      KUBE_NAMESPACE: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: cs_notprod
    commands:
      - ./ci/helm/helm-deploy.sh --values ./helm/values-notprod.yaml --values ./helm/values-demo.yaml
    depends_on:
      - checkout
    when:
      target:
        - "*-demo"

  - name: qax
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.0.0
    environment:
      KUBE_NAMESPACE: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: cs_notprod
    commands:
      - ./ci/helm/helm-deploy.sh --values ./helm/values-notprod.yaml --values ./helm/values-qax.yaml
    depends_on:
      - checkout
    when:
      target:
        - hocs-qax

  - name: preprod
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.0.0
    environment:
      KUBE_CLUSTER: acp-prod
      KUBE_NAMESPACE: ${DRONE_DEPLOY_TO}
      KUBE_SERVER: https://kube-api-prod.prod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_prod
    commands:
      - ./ci/helm/helm-deploy.sh --values ./helm/values-preprod.yaml
    depends_on:
      - checkout
    when:
      target:
        - "*-preprod"

  - name: prod
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.0.0
    environment:
      KUBE_CLUSTER: acp-prod
      KUBE_NAMESPACE: ${DRONE_DEPLOY_TO}
      KUBE_SERVER: https://kube-api-prod.prod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_prod
    commands:
      - ./ci/helm/helm-deploy.sh
    depends_on:
      - checkout
    when:
      target:
        - "*-prod"
