pipeline:

  build-project:
    image: quay.io/ukhomeofficedigital/openjdk11
    commands:
      - export SPRING_PROFILES_ACTIVE='development, local'
      - export DOCS_QUEUE_NAME='document-queue'
      - export DOCS_QUEUE_DLQ_NAME='document-queue-dlq'
      - export HOCS_URL='http://localhost:8080'
      - export HOCS_CASE_SERVICE='http://casework:8080'
      - export HOCS_DOCUMENT_SERVICE='http://documents:8080'
      - export HOCS_INFO_SERVICE='http://info:8080'
      - export DB_HOST='postgres'
      - export AWS_LOCAL_HOST='localstack'
      - ./gradlew cleanTest build --no-daemon --max-workers 2
    when:
      event: [push, pull_request, tag]

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.2
    when:
      event: [push, pull_request, tag]

  docker-build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t hocs-workflow .
    when:
      branch: [master, refs/tags/*]
      event: [push, tag]

  install-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag hocs-workflow quay.io/ukhomeofficedigital/hocs-workflow:build-$${DRONE_BUILD_NUMBER}
      - docker tag hocs-workflow quay.io/ukhomeofficedigital/hocs-workflow:latest
      - docker push quay.io/ukhomeofficedigital/hocs-workflow:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/hocs-workflow:latest
    when:
      branch: master
      event: push


  docker-semver-tag:
    image: quay.io/ukhomeofficedigital/hocs-version-bot:build-25
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_API_VERSION=1.37
    secrets:
      - github_password
      - docker_password
      - git_password
    commands:
      - /app/hocs-deploy --version=$${SEMVER} --service=hocs-workflow --serviceGitToken=$${GIT_PASSWORD} --gitToken=$${GITHUB_PASSWORD} --gitRepo="https://gitlab.digital.homeoffice.gov.uk/hocs/hocs-versions.git" --environment=qa --dockerRepository=quay.io/ukhomeofficedigital --sourceBuild=$${IMAGE_VERSION} --registryUser=ukhomeofficedigital+hocs --registryPassword=$${DOCKER_PASSWORD}
    when:
      event: deployment
      environment: qa

  clone-kube-project:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/kube-hocs-workflow.git
    when:
      event: [push, tag, deployment]

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v1.12.2
    environment:
      - KUBE_NAMESPACE=cs-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_workflow_dev
    commands:
      - cd kube-hocs-workflow
      - ./deploy.sh
    when:
      branch: master
      event: [push, tag]

  deployment:
    image: quay.io/ukhomeofficedigital/kd:v1.12.2
    environment:
      - KUBE_NAMESPACE=cs-${DRONE_DEPLOY_TO}
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_workflow_dev
      - hocs_workflow_demo
    commands:
      - cd kube-hocs-workflow
      - ./deploy.sh
    when:
      event: deployment
      environment: [dev, demo]

  deploy-to-qa:
    image: quay.io/ukhomeofficedigital/kd:v1.12.2
    environment:
      - KUBE_NAMESPACE=cs-qa
      - ENVIRONMENT=qa
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_workflow_qa
    commands:
      - source version.txt
      - echo $VERSION
      - cd kube-hocs-workflow
      - ./deploy.sh
    when:
      event: deployment
      environment: qa

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:v1.12.2
    environment:
      - KUBE_NAMESPACE=cs-prod
      - ENVIRONMENT=prod
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
    secrets:
      - hocs_workflow_prod
    commands:
      - cd kube-hocs-workflow
      - ./deploy.sh
    when:
      event: deployment
      environment: prod

services:

  postgres:
    image: quay.io/ukhomeofficedigital/postgres-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev

  localstack:
    image: localstack/localstack:latest
    environment:
      HOSTNAME_EXTERNAL: localstack
      DEFAULT_REGION: eu-west-2
      SERVICES: sns,sqs,s3

    aws_cli:
      image: garland/aws-cli-docker
      networks:
        - hocs-network
      command:
        - /bin/sh
        - -c
        - |
          aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name audit-queue
          aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name audit-queue-dlq
          aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name search-queue
          aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name search-queue-dlq
          aws --endpoint-url=http://localstack:4575 sns create-topic --name hocs-audit-topic
          aws --endpoint-url=http://localstack:4575 sns subscribe --topic-arn arn:aws:sns:eu-west-2:123456789012:hocs-audit-topic --protocol sqs --notification-endpoint arn:aws:sns:eu-west-2:123456789012:audit-queue
          aws --endpoint-url=http://localstack:4575 sns subscribe --topic-arn arn:aws:sns:eu-west-2:123456789012:hocs-audit-topic --protocol sqs --notification-endpoint arn:aws:sns:eu-west-2:123456789012:search-queue
          aws --endpoint-url=http://localstack:4575 sns list-subscriptions
          aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name document-queue
          aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name document-queue-dlq
          aws --endpoint-url=http://localstack:4572 s3 mb s3://untrusted-bucket
          aws --endpoint-url=http://localstack:4572 s3 mb s3://trusted-bucket
      environment:
        AWS_ACCESS_KEY_ID: UNSET
        AWS_SECRET_ACCESS_KEY: UNSET
        AWS_DEFAULT_REGION: 'eu-west-2'