package uk.gov.digital.ho.hocs.workflow.model;

import lombok.Getter;

public enum StageType {

    DCU_MIN_DATA_INPUT("DCU_MIN_DATA_INPUT"),
    DCU_MIN_DATA_INPUT_QA("DCU_MIN_DATA_INPUT_QA"),
    DCU_MIN_MARKUP("DCU_MIN_MARKUP"),
    DCU_MIN_TRANSFER_CONFIRMATION("DCU_MIN_TRANSFER_CONFIRMATION"),
    DCU_MIN_NO_REPLY_NEEDED_CONFIRMATION("DCU_MIN_NO_REPLY_NEEDED_CONFIRMATION"),
    DCU_MIN_INITIAL_DRAFT("DCU_MIN_INITIAL_DRAFT"),
    DCU_MIN_QA_RESPONSE("DCU_MIN_QA_RESPONSE"),
    DCU_MIN_PRIVATE_OFFICE("DCU_MIN_PRIVATE_OFFICE"),
    DCU_MIN_MINISTER_SIGN_OFF("DCU_MIN_MINISTER_SIGN_OFF"),
    DCU_MIN_DISPATCH("DCU_MIN_DISPATCH"),
    DCU_MIN_COPY_NUMBER_TEN("DCU_MIN_COPY_NUMBER_TEN"),
    DCU_TRO_DATA_INPUT("DCU_TRO_DATA_INPUT"),
    DCU_TRO_DATA_INPUT_QA("DCU_TRO_DATA_INPUT_QA"),
    DCU_TRO_MARKUP("DCU_TRO_MARKUP"),
    DCU_TRO_TRANSFER_CONFIRMATION("DCU_TRO_TRANSFER_CONFIRMATION"),
    DCU_TRO_NO_REPLY_NEEDED_CONFIRMATION("DCU_TRO_NO_REPLY_NEEDED_CONFIRMATION"),
    DCU_TRO_INITIAL_DRAFT("DCU_TRO_INITIAL_DRAFT"),
    DCU_TRO_QA_RESPONSE("DCU_TRO_QA_RESPONSE"),
    DCU_TRO_DISPATCH("DCU_TRO_DISPATCH"),
    DCU_TRO_COPY_NUMBER_TEN("DCU_TRO_COPY_NUMBER_TEN"),
    DCU_DTEN_DATA_INPUT("DCU_DTEN_DATA_INPUT"),
    DCU_DTEN_DATA_INPUT_QA("DCU_DTEN_DATA_INPUT_QA"),
    DCU_DTEN_MARKUP("DCU_DTEN_MARKUP"),
    DCU_DTEN_TRANSFER_CONFIRMATION("DCU_DTEN_TRANSFER_CONFIRMATION"),
    DCU_DTEN_NO_REPLY_NEEDED_CONFIRMATION("DCU_DTEN_NO_REPLY_NEEDED_CONFIRMATION"),
    DCU_DTEN_INITIAL_DRAFT("DCU_DTEN_INITIAL_DRAFT"),
    DCU_DTEN_QA_RESPONSE("DCU_DTEN_QA_RESPONSE"),
    DCU_DTEN_PRIVATE_OFFICE("DCU_DTEN_PRIVATE_OFFICE"),
    DCU_DTEN_DISPATCH("DCU_DTEN_DISPATCH"),
    DCU_DTEN_COPY_NUMBER_TEN("DCU_DTEN_COPY_NUMBER_TEN");

    @Getter
    private String displayValue;

    StageType(String value) {
        displayValue = value;
    }

}