---
hocs-generic-service:
  deployment:
    annotations:
      downscaler/downtime: "Mon-Sun 00:00-07:55 Europe/London,Mon-Sun 18:05-24:00 Europe/London"

  truststore:
    resources:
      requests:
        cpu: 50m

  app:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 512Mi
