package uk.gov.digital.ho.hocs.workflow.application;

public enum LogEvent {
    TASK_COMPLETED,
    CURRENT_STAGE_RETRIEVED,
    TASK_RETRIEVAL_FALURE,
    CASE_STARTED_SUCCESS,
    CASE_UPDATE_FAILURE,
    CASE_CREATION_FAILURE,
    STAGE_USER_NOT_FOUND,
    STAGE_TEAM_UPDATE_FAILURE,
    CASE_TYPE_NOT_FOUND,
    STAGE_NOT_FOUND,
    CASE_NOT_FOUND,
    CREATE_CASE_FAILURE,
    CREATE_CASE_SUCCESS,
    SECURITY_PARSE_ERROR,
    SECURITY_UNAUTHORISED,
    SECURITY_CASE_NOT_ALLOCATED_TO_USER,
    SECURITY_CASE_NOT_ALLOCATED_TO_TEAM,
    DOCUMENT_CLIENT_CREATE_SUCCESS,
    DOCUMENT_CLIENT_PROCESS_SUCCESS,
    DOCUMENT_CLIENT_FAILURE,
    DOCUMENT_CLIENT_DELETE_SUCCESS,
    UNCAUGHT_EXCEPTION;

    public static final String EVENT = "event_id";
}
