name: "Build"

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled, opened, reopened, synchronize ]
  schedule:
    - cron: '45 12 * * 1'

jobs:
  build:
    name: 'Gradle build'
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/anchore-gradle.yml@v2
    with:
      image: 'quay.io/ukhomeofficedigital/hocs-workflow'
