name: "Build"

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled, opened, reopened, synchronize ]
  schedule:
    - cron: '45 12 * * 1'

jobs:
  build:
    name: 'Gradle build'
    uses: UKHomeOffice/sas-github-workflows/.github/actions/gradle-build-project@v2
    with:
      java_version: '17'
