name: 'Docker Build Tag'
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    uses: UKHomeOffice/hocs-ci-infrastructure/.github/workflows/docker-build-tag.yml@v1
    with:
      images: 'quay.io/ukhomeofficedigital/hocs-workflow'
    secrets: inherit
