name: 'Docker Build Branch'
on:
  pull_request:
    types: [ labeled, opened, reopened, synchronize ]

jobs:
  publish:
    name: 'Branch Publish'
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'smoketest') == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USER_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Calculate metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: quay.io/ukhomeofficedigital/hocs-workflow
          tags: |
            type=raw,value=${{ github.event.pull_request.head.sha }}

      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
