name: 'Docker Build Tag'
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    uses: UKHomeOffice/hocs-github-actions/.github/workflows/docker-build-tag-gradle.yml@v3
    with:
      images: 'quay.io/ukhomeofficedigital/hocs-workflow'
    secrets: inherit
