name: 'SemVer Tag and Docker Build'
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/semver-tag-docker-gradle.yml@v2
    with:
      image: 'quay.io/ukhomeofficedigital/hocs-workflow'
    secrets: inherit
