name: 'Test'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/test-gradle.yml@v1
    with:
      dockerComposeComponents: 'localstack postgres'
    secrets: inherit
