name: "Trivy Scan"

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled, opened, reopened, synchronize ]
  schedule:
    - cron: '45 12 * * 1'

jobs:
  scan:
    steps:
      - name: 'Gradle build'
        uses: UKHomeOffice/sas-github-workflows/.github/actions/gradle-build-project@v2
        with:
          java_version: '17'
      - name: 'Trivy scans'
        uses: UKHomeOffice/sas-github-workflows/.github/workflows/trivy.yml@v2
        with:
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          checkoutSubmodule: true
        secrets: inherit
