name: "Trivy Scan"

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled, opened, reopened, synchronize ]
  schedule:
    - cron: '45 12 * * 1'

jobs:
  scan:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/trivy-gradle.yml@ca086e781373818642d6d04731a35c86903347bf
    with:
      severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      checkoutSubmodule: true
    secrets: inherit
