name: "Trivy Scan"

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled, opened, reopened, synchronize ]
  schedule:
    - cron: '45 12 * * 1'

jobs:
  scan:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/trivy-gradle.yml@66c5e704acd6efe400df4b8caf57fae6f4e7f0f8
    with:
      severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      checkoutSubmodule: true
    secrets: inherit
