name: "Trivy Scan"

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled, opened, reopened, synchronize ]
  schedule:
    - cron: '45 12 * * 1'

jobs:
  scan:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/trivy-gradle.yml@337c618b21d80045a99e7769035e5268592d350c
    with:
      severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      checkoutSubmodule: true
    secrets: inherit
